# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
bashrc_location = '/home/vagrant/.bashrc'
# Load variables from YAML files
require 'yaml'
dir = File.dirname(File.expand_path(__FILE__))
settings = YAML::load_file("#{dir}/env.yml")

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.hostname = settings["vm"]["hostname"]
  config.vm.box = settings["vm"]["image"]
  config.vm.box_check_update = false
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = settings["vm"]["memory"]
    libvirt.cpus = settings["vm"]["cpus"]
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> #{bashrc_location}
    source #{bashrc_location}
  SHELL
  config.vm.provision :shell, :path => "zypper/install.sh"
  config.vm.provision :shell, :path => "k3s/install.sh", :args => [settings["k3s"]["version"]]
  config.vm.provision :shell, :path => "helm/install.sh", :args => [settings["helm"]["version"]]
  config.vm.provision :shell, :path => "epinio/install.sh", :args => [settings["epinio"]["cli_version"]]
  if settings["rancher"]["provision_rancher"] == true then
    config.vm.provision :shell, :path => "rancher/install.sh", :args => [settings["vm"]["hostname"], settings["rancher"]["dashboard_version"]]
  end
  if settings["epinio"]["helm_chart_dev_version"] == true then
    config.vm.provision :shell, :path => "chartmuseum/install.sh", :args => [settings["vm"]["hostname"]], :privileged => false
  end
end
