name: Vagrant validate

on:
  push:
  pull_request:
    branches: [main]
    paths:
    - 'eks-box'
    - 'k3s-epinio-1-node'

jobs:
  vagrant-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Vagrant
        run: |
          sudo apt install vagrant
      - name: Validate Vagrantfile
        run: |
          cd eks-box
          mv secrets.yml-template secrets.yml
          vagrant validate
          cd ../k3s-epinio-1-node
          vagrant validate
