name: Vagrantfiles check

on: pull_request

jobs:
  vagrantfiles-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Vagrant
        run: |
          sudo apt install vagrant
      - name: Validate vagrantfiles
        run: |
          cd eks-box
          mv secrets.yml-template secrets.yml
          vagrant validate
          cd ../k3s-epinio-1-node
          vagrant validate
